config/routes.rb
Rails.application.routes.draw do
  root to: 'refund_requests#index'

  devise_for :users

  resources :users, only: [:index]

  resources :refund_requests, only: [:index, :show, :update, :new, :create, :destroy]

  resources :categories, only: [:index, :edit, :update, :new, :create, :destroy]

end

app/models/refund_request.rb
class RefundRequest < ActiveRecord::Base
  extend Filterable

  belongs_to :category
  belongs_to :user

  validates :user, presence: true
  validates :category, presence: true

  validates :description, presence: true
  validates :title, presence: true, length: { maximum: 50 }

  validates :amount, numericality: { greater_than: 0 }

  enum status: { pending: 0, accepted: 1, rejected: 2 }
  validates :status, presence: true

  validates :rejection_reason, presence: true, if: 'rejected?'

  validate :edit_only_if_pending, on: :update

  def refunded_amount
    amount * category.refund_percentage / 100
  end

  def self.monthly_summary(month, year)
    month_start = Date.new(year, month)
    month_end = month_start.end_of_month
    RefundRequest
      .accepted
      .joins('JOIN users ON refund_requests.user_id = users.id')
      .joins('JOIN categories ON refund_requests.category_id = categories.id')
      .select(:user_id, :full_name, 'sum(cast((amount * refund_percentage / 100) as decimal(5,2))) total_refunds')
      .where(created_at: month_start..month_end)
      .group(:user_id, :full_name)
  end

  private

    def self.allowed_filters
      [:user, :category, :status]
    end

    def edit_only_if_pending
      if changes.except(:status, :rejection_reason).present? && !pending?
        errors.add(:base, 'cannot be edited if already accepted or rejected')
      end
    end

end

app/controllers/refund_requests_controller.rb
class RefundRequestsController < ApplicationController
  before_action :only_admin_can_filter_users, only: :index

  def index
    authorize RefundRequest
    @refund_requests = policy_scope(RefundRequest).filter(params)
    @refund_requests = @refund_requests
    @refund_requests = paginate(@refund_requests).decorate
  end

  def show
    @refund_request = RefundRequest.find(params[:id]).decorate
    authorize @refund_request
  end

  def new
    @refund_request = RefundRequest.new
    authorize @refund_request
    @refund_request.user = current_user
  end

  def create
    @refund_request = RefundRequest.new(user: current_user)
    authorize @refund_request
    @refund_request.assign_attributes(permitted_attributes(@refund_request))
    if @refund_request.save
      redirect_to refund_requests_path,
                  notice: 'Refund request has been created'
    else
      render :new, flash: { error: 'Refund request could not be created' }
    end
  end

  def edit
    @refund_request = RefundRequest.find(params[:id]).decorate
    authorize @refund_request
  end

  def update
    @refund_request = RefundRequest.find(params[:id]).decorate
    authorize @refund_request
    if @refund_request.update_attributes(permitted_attributes(@refund_request))
      flash.now[:notice] = 'Refund request has been updated'
      render :show
    else
      render :show, flash: { error: 'Refund request could not be updated' }
    end
  end

  def destroy
    @refund_request = RefundRequest.find(params[:id])
    authorize @refund_request
    if @refund_request.destroy
      redirect_to refund_requests_path, notice: 'Refund request has been deleted'
    else
      redirect_to refund_request_path(@refund_request),
                  flash: { error: 'Refund request could not be deleted' }
    end
  end

  private

    def only_admin_can_filter_users
      unless user_signed_in? && current_user.admin?
        params.except!(:user)
      end
    end

end

app/helpers/refund_request_helper.rb
module RefundRequestHelper
  def filters_tag
    haml_tag :div, class: 'filters' do
      allowed_model_filters.each { |key, value| model_filter_button key, value }
      allowed_field_filters.each { |field| field_filter_button field }
    end
    haml_tag :h5 do
      haml_concat "To apply filtering by
                   #{current_user.admin? ? 'user, ' : ''}
                   category or status, click on the respective field."
    end unless any_filter?
  end

  def add_filter_url(filter)
    refund_requests_path(params_plus(filter))
  end

  def params_without(param)
    params.slice(*allowed_params).except(param)
  end

  def params_plus(param)
    params.slice(*allowed_params).merge(param)
  end

  private

    def allowed_model_filters
      { Category => :title, User => :full_name }
    end

    def allowed_field_filters
      [:status]
    end

    def allowed_params
      allowed_model_filters.keys.map { |k| k.model_name.param_key } + allowed_field_filters
    end

    def any_filter?
      params.slice(*allowed_params).present?
    end

    def model_filter_button(model_class, attr)
      param_key = model_class.model_name.param_key
      haml_tag :a, class: 'btn btn-xs btn-primary', type: 'button',
                   href: refund_requests_path(params_without(param_key)) do
        haml_concat "#{model_class.model_name.human}: "
        haml_tag :strong do
          haml_concat "#{model_class.find(params[param_key]).send attr}"
        end
        haml_tag :span, class: 'badge', style: 'font-size: 7pt' do
          haml_tag :span, class: 'glyphicon glyphicon-remove', 'aria-hidden': true
        end
      end if params[param_key].present?
    end

    def field_filter_button(field)
      param_key = field
      haml_tag :a, class: 'btn btn-xs btn-primary', type: 'button',
                   href: refund_requests_path(params_without(param_key)) do
        haml_concat "#{field}: "
        haml_tag :strong do
          haml_concat params[param_key]
        end
        haml_tag :span, class: 'badge', style: 'font-size: 7pt' do
          haml_tag :span, class: 'glyphicon glyphicon-remove', 'aria-hidden': true
        end
      end if params[param_key].present?
    end


end

app/views/refund_requests/_form.html.haml
.authform
  = simple_form_for @refund_request do |f|
    - if @refund_request.errors.any?
      #error_explanation
        %h2= "#{pluralize(@refund_request.errors.count, "error")} prohibited this refund request from being saved:"
        %ul
          - @refund_request.errors.full_messages.each do |msg|
            %li= msg
    .form-group
      = f.input :title, as: :string, autofocus: true, disabled: !@refund_request.pending?
    .form-group
      = f.input :description, disabled: !@refund_request.pending?
    .form-group
      = f.input :category_id, collection: Category.all, selected: @refund_request.category_id, as: :select, disabled: !@refund_request.pending?
    .form-group
      = f.input :amount, step: 0.01, disabled: !@refund_request.pending?
    - unless current_page?(action: 'new')
      .check-boxes
        = f.input :status, selected: RefundRequest.statuses.keys[@refund_request[:status]], disabled: !current_user.admin?
      .form-group
        = f.input :rejection_reason, class: 'form-control', disabled: !current_user.admin?
    .actions
      = f.submit 'Save', :class => 'btn btn-primary'

app/views/refund_requests/index.html.haml
%h1 Refund Requests
%h4
  - filters_tag

%table.table
  %thead
    %tr
      - if user_signed_in? && current_user.admin?
        %th User
      %th Name
      %th Category
      %th Amount
      %th Refund
      %th Submitted
      %th Status
      - if user_signed_in? && current_user.admin?
        %th

  %tfoot
    %tr
      %td.text-center{colspan: 8}
        =paginate @refund_requests

  %tbody
    - @refund_requests.each do |refund_request|
      %tr
        - if user_signed_in? && current_user.admin?
          %td= refund_request.user
        %td= refund_request.details_link
        %td= refund_request.category
        %td= refund_request.amount_currency
        %td= refund_request.refund
        %td= refund_request.created_at
        %td= refund_request.status
        - if user_signed_in? && current_user.admin?
          %td= refund_request.delete_link


%br

= link_to 'New Refund request', new_refund_request_path

app/views/refund_requests/new.html.haml
%h1 New refund request

= render 'form'

= link_to 'Back', refund_requests_path

app/views/refund_requests/show.html.haml
%h1= "Refund request: #{@refund_request.title}"

= render 'form'

= link_to 'Back', refund_requests_path