config/routes.rb
Rails.application.routes.draw do
  root to: 'refund_requests#index'

  devise_for :users

  resources :users, only: [:index]

  resources :refund_requests, only: [:index, :show, :update, :new, :create, :destroy]

  resources :categories, only: [:index, :edit, :update, :new, :create, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :refund_requests

  validates :title, presence: true, uniqueness: true
  validates :refund_percentage, numericality: { greater_than: 0,
                                                less_than_or_equal_to: 100 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    authorize Category
    @categories = Category.all
    @categories = paginate(@categories).decorate
  end

  def edit
    @category = Category.find(params[:id])
    authorize @category
  end

  def update
    @category = Category.find(params[:id]).decorate
    authorize @category
    if @category.update_attributes(category_params)
      redirect_to categories_url, notice: 'Category has been updated'
    else
      render :update, flash: { error: 'Category could not be updated' }
    end
  end

  def new
    @category = Category.new
    authorize @category
  end

  def create
    @category = Category.new(category_params).decorate
    authorize @category
    if @category.save
      redirect_to categories_url, notice: 'Category has been created'
    else
      render :new, flash: { error: 'Category could not be created' }
    end
  end

  def destroy
    @category = Category.find(params[:id])
    authorize @category
    if @category.destroy
      redirect_to categories_url, notice: 'Category has been deleted'
    else
      redirect_to categories_url, notice: 'Category could not be deleted'
    end
  end

  private

    def category_params
      params.require(:category).permit(:title, :refund_percentage)
    end

end

app/views/categories/_form.html.haml
.authform
  = form_for @category do |f|
    - if @category.errors.any?
      #error_explanation
        %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
        %ul
          - @category.errors.full_messages.each do |msg|
            %li= msg
    .form-group
      = f.label :title
      = f.text_field :title, autofocus: true, class: 'form-control'
    .form-group
      = f.label :refund_percentage
      = f.number_field :refund_percentage, class: 'form-control', min: 1, max: 100

    .actions
      = f.submit 'Save', :class => 'btn btn-primary'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Categories

%table.table
  %thead
    %tr
      %th Title
      %th Refund percentage
      %th
      %th

  %tfoot
    %tr
      %td.text-center{colspan: 8}
        =paginate @categories

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.title
        %td= category.refund_percentage
        %td= category.edit_link
        %td= category.delete_link

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path