config/routes.rb
Rails.application.routes.draw do
  root to: 'refund_requests#index'

  devise_for :users

  resources :users, only: [:index]

  resources :refund_requests, only: [:index, :show, :update, :new, :create, :destroy]

  resources :categories, only: [:index, :edit, :update, :new, :create, :destroy]

end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .row
      .col-md-10.col-md-offset-1
        .navbar-header
          %button.navbar-toggle.collapsed{'data-toggle' => 'collapse', 'data-target' => '#navbar'}
            %span.sr-only Toggle navigation
            - 3.times do
              %span.icon-bar
          = link_to root_path, class: 'navbar-brand' do
            %span.glyphicon.glyphicon-eur
            RefundClerk
        .navbar-collapse.collapse#navbar
          %ul.nav.navbar-nav
            - if user_signed_in?
              - if current_user.admin?
                %li= link_to "All requests", refund_requests_path
                %li= link_to "Users", users_path
                %li= link_to "Categories", categories_path
              - else
                %li= link_to "My requests", refund_requests_path

          %ul.nav.navbar-nav.navbar-right
            %li.dropdown

              %a.dropdown-toggle{href: '#', 'data-toggle' => 'dropdown'}
                = user_signed_in? ? current_user.full_name : "Account"
                %b.caret
              %ul.dropdown-menu
                - if user_signed_in?
                  %li
                    =link_to "Edit account", edit_user_registration_path
                  %li
                    =link_to "Sign out", destroy_user_session_path, method: :delete
                - else
                  %li
                    =link_to "Sign in", new_user_session_path
                  %li
                    =link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RefundClerk
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'

    .container
      .row
        .col-md-10.col-md-offset-1
          - flash.each do |type, message|
            .alert{class: bootstrap_class_for(type)}
              = message
      .row
        .col-md-10.col-md-offset-1
          = yield